[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y chromium chromium-chromedriver xvfb",
    "ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver",
    "chromium --version",
    "chromedriver --version"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"