[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget",
    "echo 'WebDriver Manager will handle ChromeDriver automatically'"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"